DROP TABLE CRIMINAL;
DROP TABLE IDENTIFICA;
DROP TABLE PISTA;
DROP TABLE OBTIENE;
DROP TABLE LUGAR;
DROP TABLE CIUDAD;
DROP TABLE PROXIMOS;

CREATE TABLE CRIMINAL (
idCriminal INTEGER NOT NULL,
nombreCriminal varchar(50) NOT NULL,
hobbie VARCHAR(50) NOT NULL,
sexo varchar(50) NOT NULL,
colorPelo VARCHAR(50) NOT NULL,
ocupacion varchar(50) NOT NULL,
vehiculo VARCHAR(50) NOT NULL,
caracteristicas VARCHAR(50) NOT NULL,
PRIMARY KEY (idCriminal)
);

CREATE TABLE PISTA (
idPista INTEGER NOT NULL,
descripcion VARCHAR(255) NOT NULL,
PRIMARY KEY (idPista)
);


