CREATE DATABASE Taller2CarmenSandiego

DROP TABLE CRIMINAL IF EXISTS ;
DROP TABLE IDENTIFICA IF EXISTS ;
DROP TABLE PISTA IF EXISTS ;
DROP TABLE OBTIENE IF EXISTS ;
DROP TABLE LUGAR IF EXISTS ;
DROP TABLE CIUDAD IF EXISTS ;
DROP TABLE PROXIMOS IF EXISTS ;

CREATE TABLE CRIMINAL (
idCriminal INTEGER NOT NULL,
nombreCriminal varchar(50) NOT NULL,
hobbie VARCHAR(50) NOT NULL,
sexo varchar(50) NOT NULL,
colorPelo VARCHAR(50) NOT NULL,
ocupacion varchar(50) NOT NULL,
vehiculo VARCHAR(50) NOT NULL,
caracteristicas VARCHAR(50) NOT NULL,
PRIMARY KEY (clienteId)
);

CREATE TABLE IDENTIFICA(
FOREIGN KEY (idCriminal) REFERENCES CRIMINAL (idCriminal),
FOREIGN KEY (idPista) REFERENCES PISTA(idPista)
);

CREATE TABLE PISTA (
idPista INTEGER NOT NULL,
descripcion VARCHAR(255) NOT NULL,
PRIMARY KEY (idPista),
);
